version: '3.8'
services:
  motorhead:
    image: ghcr.io/getmetal/motorhead:v2.0.2
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - MOTORHEAD_LONG_TERM_MEMORY=true
    env_file:
      - .env

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
